server:
  port: 8082
  servlet:
    context-path: /demo 
    
spring:
  datasource:
    datasource-write:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/demowrite?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: twj
      password: qwer1234
    datasource-readA:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/demoreada?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: twj
      password: qwer1234
    datasource-readB:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/demowreadb?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: twj
      password: qwer1234
      
      
    datasource-selectA:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/demoselecta?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: twj
      password: qwer1234
    datasource-selectB:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/demoselectb?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: twj
      password: qwer1234
      
mybatis:
  config-location: mybatis-config.xml
  mapper-locations: mappers/**Mapper.xml
  type-aliases-package: com.example.SBdemo.model
